/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertOkCancel: typeof import('./src/components/AlertOkCancel.vue')['default']
    DateInput: typeof import('./src/components/dateInput.vue')['default']
    EnergyLabelSearch: typeof import('./src/components/EnergyLabelSearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
